coverage:
  status:
    project:
      default:
        target: 97%
        threshold: 0%
        informational: false
    patch:
      default:
        informational: false
        target: 97%
        threshold: 0%

comment: #this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  hide_project_coverage: false
  require_changes: true
