export enum Response {
	PRCODE = "PRCODE",
	SRCODE = "SRCODE",
	RESULTTEXT = "RESULTTEXT",
	EXPIRY = "EXPIRY",
	ACSRES = "ACSRES",
	ACCODE = "ACCODE",
	DAYTOCAPTURE = "DAYTOCAPTURE",
	TOKENREGSTATUS = "TOKENREGSTATUS",
	DIGEST1 = "DIGEST1",
}
