name: Pull Request Checks

on:
  pull_request

jobs:
  lint-and-format:
    name: Lint and Format with Biome
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache-dependency-path: pnpm-lock.yaml
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint all packages
        run: npx lerna run lint --stream --concurrency 1

      - name: Format check all packages
        run: npx lerna run format --stream --concurrency 1

      - name: Typecheck all packages
        run: npx lerna run typecheck --stream --concurrency 1


  test:
    name: Run Tests and Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache-dependency-path: pnpm-lock.yaml
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests with coverage
        run: pnpm run test:coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
